# Generated by Django 3.0.8 on 2020-07-31 21:00

import car.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('model_car', models.IntegerField(default=1900)),
                ('car_type', models.CharField(choices=[('sedan', 'sedan'), ('hatchBack', 'hatchBack'), ('coupe', 'coupe'), ('crossover', 'crossover')], max_length=15)),
                ('descreption', models.TextField(max_length=1000)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('mileage', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('engine', models.IntegerField(default=1)),
                ('bid_on', models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=30)),
                ('color', models.CharField(max_length=15)),
                ('Category', models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Crashed', 'Crashed')], max_length=50)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('manual', 'manual')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=car.models.image_upload)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apply_For',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('link', models.URLField()),
                ('cv', models.FileField(upload_to='apply')),
                ('coverL', models.TextField(max_length=500)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='car.Job')),
            ],
        ),
    ]
