# Generated by Django 3.0.8 on 2020-07-31 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_job_image_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image_a',
        ),
    ]
