# Generated by Django 3.0.8 on 2020-08-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20200731_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_bid', models.IntegerField(default=0)),
            ],
        ),
    ]
