# Generated by Django 3.0.8 on 2020-08-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_bid_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid_price',
            old_name='price_bid',
            new_name='bid_price',
        ),
    ]
