# Generated by Django 3.0.8 on 2020-08-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_bid_price_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid_price',
            name='name',
        ),
    ]
