# Generated by Django 3.0.8 on 2020-08-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_bid_price_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid_price',
            name='name',
        ),
    ]
