# Generated by Django 3.0.8 on 2020-08-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_bid_price_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid_price',
            name='owner',
        ),
    ]
