# Generated by Django 3.0.8 on 2020-08-01 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0013_remove_bid_price_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid_price',
            name='user_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
