# Generated by Django 3.0.8 on 2020-08-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0015_remove_bid_price_user_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid_price',
            name='user_bider',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
