# Generated by Django 3.0.8 on 2020-08-01 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_bid_price_user_bider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid_price',
            name='user_bider',
        ),
    ]
