# Generated by Django 3.0.8 on 2020-08-01 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0017_remove_bid_price_user_bider'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid_price',
            name='owner_bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_bid', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
