# Generated by Django 3.0.8 on 2020-08-01 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0018_bid_price_owner_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid_price',
            name='owner_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
