# Generated by Django 3.0.8 on 2020-08-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0020_auto_20200801_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bid_on',
            field=models.CharField(choices=[('On_Bid', 'On_Bid'), ('Coming_Soon', 'Coming_Soon')], max_length=30),
        ),
    ]
